export type PresetGroupId =
  | "osobliwosci"
  | "przeplyw"
  | "dynamika"
  | "czas"
  | "misy";

export type FieldPreset = {
  id: string;
  name: string;
  blurb: string;
  fx: string;
  fy: string;
  domain: number;
  group: PresetGroupId;
  featured?: boolean;
};

export const PRESET_GROUPS: { id: PresetGroupId; name: string }[] = [
  { id: "osobliwosci", name: "Osobliwości" },
  { id: "przeplyw", name: "Przepływ" },
  { id: "dynamika", name: "Dynamika" },
  { id: "czas", name: "Czasowe" },
  { id: "misy", name: "Rezonans" },
];

export const PRESETS: FieldPreset[] = [
  {
    id: "wir",
    name: "Wir",
    blurb: "Czysty obrót wokół początku",
    fx: "-y",
    fy: "x",
    domain: 4,
    group: "osobliwosci",
    featured: true,
  },
  {
    id: "zrodlo",
    name: "Źródło",
    blurb: "Odpływ na zewnątrz",
    fx: "x",
    fy: "y",
    domain: 4,
    group: "osobliwosci",
    featured: true,
  },
  {
    id: "ujscie",
    name: "Ujście",
    blurb: "Zbieganie do środka",
    fx: "-x",
    fy: "-y",
    domain: 4,
    group: "osobliwosci",
  },
  {
    id: "siodlo",
    name: "Siodło",
    blurb: "Niestabilny punkt hiperboliczny",
    fx: "x",
    fy: "-y",
    domain: 4,
    group: "osobliwosci",
    featured: true,
  },
  {
    id: "spirala",
    name: "Spirala",
    blurb: "Wir z przyciąganiem",
    fx: "-y - 0.35*x",
    fy: "x - 0.35*y",
    domain: 4,
    group: "osobliwosci",
  },
  {
    id: "ognisko",
    name: "Ognisko",
    blurb: "Spirala rozbiegająca się",
    fx: "-y + 0.45*x",
    fy: "x + 0.45*y",
    domain: 4,
    group: "osobliwosci",
  },
  {
    id: "eliptyczny",
    name: "Elipsa",
    blurb: "Wydłużone orbity harmoniczne",
    fx: "-0.5*y",
    fy: "2*x",
    domain: 4,
    group: "osobliwosci",
  },
  {
    id: "prad",
    name: "Prąd",
    blurb: "Równomierne pole poziome",
    fx: "1",
    fy: "0",
    domain: 4,
    group: "osobliwosci",
  },
  {
    id: "scinanie",
    name: "Ścinanie",
    blurb: "Warstwy przesuwają się",
    fx: "y",
    fy: "0",
    domain: 4,
    group: "osobliwosci",
  },
  {
    id: "magnetyczny",
    name: "Przewód",
    blurb: "Pole wokół pionowego prądu",
    fx: "-y / (x^2 + y^2 + 0.08)",
    fy: "x / (x^2 + y^2 + 0.08)",
    domain: 4,
    group: "osobliwosci",
  },
  {
    id: "dipol",
    name: "Dipol",
    blurb: "Dwa bieguny w początku",
    fx: "(x^2 - y^2) / (x^2 + y^2 + 0.12)^2",
    fy: "2*x*y / (x^2 + y^2 + 0.12)^2",
    domain: 4,
    group: "osobliwosci",
    featured: true,
  },
  {
    id: "grawitacja",
    name: "Grawitacja",
    blurb: "Przyciąganie jak 1/r²",
    fx: "-x / (x^2 + y^2 + 0.2)^1.5",
    fy: "-y / (x^2 + y^2 + 0.2)^1.5",
    domain: 4,
    group: "osobliwosci",
  },
  {
    id: "kwadrupol",
    name: "Kwadrupol",
    blurb: "Cztery płatki, Re(z³)",
    fx: "x^3 - 3*x*y^2",
    fy: "3*x^2*y - y^3",
    domain: 2.5,
    group: "osobliwosci",
  },
  {
    id: "zrodlo-wir",
    name: "Źródło-wir",
    blurb: "Odpływ skręcony w spiralę",
    fx: "(x - y) / (x^2 + y^2 + 0.16)",
    fy: "(y + x) / (x^2 + y^2 + 0.16)",
    domain: 4,
    group: "osobliwosci",
  },
  {
    id: "podwojny",
    name: "Dwa wiry",
    blurb: "Para przeciwbieżnych wirów",
    fx: "-(y-1.4)/(x^2+(y-1.4)^2+0.16) + (y+1.4)/(x^2+(y+1.4)^2+0.16)",
    fy: "(x)/(x^2+(y-1.4)^2+0.16) - (x)/(x^2+(y+1.4)^2+0.16)",
    domain: 5,
    group: "osobliwosci",
  },
  {
    id: "gyre",
    name: "Gyre",
    blurb: "Zamknięte wiry komórkowe",
    fx: "-pi*sin(pi*x)*cos(pi*y)",
    fy: "pi*cos(pi*x)*sin(pi*y)",
    domain: 2,
    group: "przeplyw",
    featured: true,
  },
  {
    id: "taylor",
    name: "Taylor–Green",
    blurb: "Siatka przeciwnych wirów",
    fx: "-sin(x)*cos(y)",
    fy: "cos(x)*sin(y)",
    domain: 3.2,
    group: "przeplyw",
  },
  {
    id: "walec",
    name: "Walec",
    blurb: "Opływ walca: prąd + dipol",
    fx: "1 - (x^2 - y^2) / (x^2 + y^2 + 0.25)^2",
    fy: "-2*x*y / (x^2 + y^2 + 0.25)^2",
    domain: 4,
    group: "przeplyw",
  },
  {
    id: "dzet",
    name: "Dżet",
    blurb: "Wąski poziomy strumień",
    fx: "1 / cosh(y)^2",
    fy: "0",
    domain: 4,
    group: "przeplyw",
  },
  {
    id: "warstwa",
    name: "Warstwa",
    blurb: "Ścinanie z lekką falą",
    fx: "tanh(2*y)",
    fy: "0.2*sin(pi*x)",
    domain: 3,
    group: "przeplyw",
  },
  {
    id: "lamb",
    name: "Lamb",
    blurb: "Wir Gaussa, gasnący z r",
    fx: "-y * exp(-(x^2 + y^2) / 2)",
    fy: "x * exp(-(x^2 + y^2) / 2)",
    domain: 4,
    group: "przeplyw",
  },
  {
    id: "stagnacja",
    name: "Stagnacja",
    blurb: "Punkt spiętrzenia, potencjał z²",
    fx: "x^2 - y^2",
    fy: "-2*x*y",
    domain: 3,
    group: "przeplyw",
  },
  {
    id: "komorki",
    name: "Komórki",
    blurb: "Podwójny gyre oceaniczny",
    fx: "-pi*sin(pi*x)*cos(pi*y)",
    fy: "pi*cos(pi*x)*sin(pi*y) - 0.25*pi*sin(2*pi*x)",
    domain: 2,
    group: "przeplyw",
  },
  {
    id: "wahadlo",
    name: "Wahadło",
    blurb: "Portret fazowy: (θ, ω)",
    fx: "y",
    fy: "-sin(x)",
    domain: 8,
    group: "dynamika",
    featured: true,
  },
  {
    id: "wahadlo-tlumione",
    name: "Tłumione",
    blurb: "Wahadło z tarciem",
    fx: "y",
    fy: "-sin(x) - 0.22*y",
    domain: 8,
    group: "dynamika",
  },
  {
    id: "vanderpol",
    name: "Van der Pol",
    blurb: "Nieliniowy cykl graniczny",
    fx: "y",
    fy: "0.7*(1 - x^2)*y - x",
    domain: 4,
    group: "dynamika",
    featured: true,
  },
  {
    id: "hopf",
    name: "Hopf",
    blurb: "Okrągły atraktor",
    fx: "x - y - x*(x^2 + y^2)",
    fy: "x + y - y*(x^2 + y^2)",
    domain: 3,
    group: "dynamika",
    featured: true,
  },
  {
    id: "duffing",
    name: "Duffing",
    blurb: "Studnia podwójna, homoklinika",
    fx: "y",
    fy: "x - x^3 - 0.28*y",
    domain: 3,
    group: "dynamika",
  },
  {
    id: "rayleigh",
    name: "Rayleigh",
    blurb: "Cykl z nieliniowym tarciem",
    fx: "y",
    fy: "-x + y*(1 - y^2)",
    domain: 3,
    group: "dynamika",
  },
  {
    id: "lotka",
    name: "Lotka–Volterra",
    blurb: "Drapieżnik i ofiara",
    fx: "x*(1.2 - y)",
    fy: "y*(x - 0.8)",
    domain: 3.5,
    group: "dynamika",
  },
  {
    id: "fitzhugh",
    name: "FitzHugh–Nagumo",
    blurb: "Neuron: pobudzenie i powrót",
    fx: "x - x^3/3 - y",
    fy: "0.08*(x + 0.7 - 0.8*y)",
    domain: 3,
    group: "dynamika",
  },
  {
    id: "brusselator",
    name: "Brusselator",
    blurb: "Oscylator chemiczny",
    fx: "1 + x^2*y - 4*x",
    fy: "3*x - x^2*y",
    domain: 4,
    group: "dynamika",
  },
  {
    id: "oddech",
    name: "Oddech",
    blurb: "Wir, który pulsuje w czasie",
    fx: "-y*(1 + 0.4*sin(t))",
    fy: "x*(1 + 0.4*sin(t))",
    domain: 4,
    group: "czas",
  },
  {
    id: "fala",
    name: "Fala",
    blurb: "Prąd z biegnącą falą",
    fx: "1",
    fy: "0.55*sin(x - t)",
    domain: 6,
    group: "czas",
  },
  {
    id: "wymuszone",
    name: "Wymuszone",
    blurb: "Wahadło pchnięte cos(t)",
    fx: "y",
    fy: "-sin(x) + 0.45*cos(t)",
    domain: 8,
    group: "czas",
  },
  {
    id: "dryf",
    name: "Dryf",
    blurb: "Wir z kołyszącym prądem",
    fx: "-y + 0.4*sin(t)",
    fy: "x",
    domain: 4,
    group: "czas",
  },
  {
    id: "misa",
    name: "Obręcz",
    blurb: "Wir na krawędzi — rezonans na pierścieniu",
    fx: "-y * exp(-((r - 2.1)^2) / 0.4)",
    fy: "x * exp(-((r - 2.1)^2) / 0.4)",
    domain: 4,
    group: "misy",
  },
  {
    id: "gong",
    name: "Gong",
    blurb: "Uderzenie: kręgi rozchodzą się ze środka",
    fx: "cos(r - 1.15*t) * x / (r + 0.2)",
    fy: "cos(r - 1.15*t) * y / (r + 0.2)",
    domain: 5,
    group: "misy",
  },
  {
    id: "om",
    name: "Spokój",
    blurb: "Miękki oddech obrotu — uspokojenie",
    fx: "-y * exp(-r^2 / 10) * (0.7 + 0.18*sin(0.45*t))",
    fy: "x * exp(-r^2 / 10) * (0.7 + 0.18*sin(0.45*t))",
    domain: 4,
    group: "misy",
  },
  {
    id: "sen",
    name: "Sen",
    blurb: "Spirala do środka, cichnie",
    fx: "-0.22*x - 0.55*y",
    fy: "-0.22*y + 0.55*x",
    domain: 4,
    group: "misy",
  },
  {
    id: "swit",
    name: "Świt",
    blurb: "Spirala na zewnątrz — pobudzenie",
    fx: "0.38*x - y",
    fy: "0.38*y + x",
    domain: 4,
    group: "misy",
  },
  {
    id: "mantra",
    name: "Obieg",
    blurb: "Fala obiega brzeg",
    fx: "-y / (r + 0.15) * sin(4*theta - t)",
    fy: "x / (r + 0.15) * sin(4*theta - t)",
    domain: 4,
    group: "misy",
  },
  {
    id: "bicie",
    name: "Bicie",
    blurb: "Dwa tony, lekko rozstrojone",
    fx: "(sin(r - t) + sin(r - 1.08*t)) * x / (r + 0.2)",
    fy: "(sin(r - t) + sin(r - 1.08*t)) * y / (r + 0.2)",
    domain: 5,
    group: "misy",
  },
  {
    id: "harmonia",
    name: "Harmonia",
    blurb: "Cztery płatki — podstawowy ton",
    fx: "cos(4*theta) * sin(pi*r / 3) * cos(t) * x / (r + 0.15)",
    fy: "cos(4*theta) * sin(pi*r / 3) * cos(t) * y / (r + 0.15)",
    domain: 4,
    group: "misy",
  },
  {
    id: "kropla",
    name: "Kropla",
    blurb: "Ripple po uderzeniu, gaśnie z r",
    fx: "exp(-0.18*r) * sin(2.1*r - 1.35*t) * x / (r + 0.18)",
    fy: "exp(-0.18*r) * sin(2.1*r - 1.35*t) * y / (r + 0.18)",
    domain: 5,
    group: "misy",
  },
  {
    id: "pobudka",
    name: "Pobudka",
    blurb: "Szybsze kręgi, jaśniejszy ton",
    fx: "sin(2.8*r - 2.1*t) * x / (r + 0.2) - 0.35*y",
    fy: "sin(2.8*r - 2.1*t) * y / (r + 0.2) + 0.35*x",
    domain: 4,
    group: "misy",
  },
];

export const DEFAULT_PRESET = PRESETS[0]!;

export const FEATURED_PRESETS = PRESETS.filter((p) => p.featured);
